In [4]:
import math as m
import numpy as n

def x_comp(mag,angle):
    ang =m.radians(angle)
    x = mag*(m.cos(ang))
    return x

def y_comp(mag,angle):
    ang =m.radians(angle)
    y = mag*(m.sin(ang))
    return y

def magnitude(x,y):
    mag = m.sqrt((x**2+y**2))
    return mag

def dot(a, b, angle):
    ang =m.radians(angle)
    product = (a*b)*(m.cos(ang))
    return product

def cross(a, b, angle):
    ang =m.radians(angle)
    product = (a*b)*(m.sin(ang))
    return product

def tan_angle(x, y):
    pi = 3.14
    radians = m.atan(y/x)
    degree = radians*(180/pi)
    return degree

def cos_angle(x,y):
    pi = 3.14
    radians = m.acos(x/y)
    degree = radians*(180/pi)
    return degree

#  VECTORS

# 1. A displacement vector in the xy plane is 7.3 m long and directed at angle of 30° in Fig.1. Determine (a) the x component and (b) the y component of the vector.

In [2]:
print("X-COMPONENT")
x_comp(7.3,30)

X-COMPONENT


6.321985447626402

In [3]:
print("Y-COMPONENT")
y_comp(7.3,30)

Y-COMPONENT


3.6499999999999995

## 2. The two vectors a and b in Fig-2 have equal magnitudes of 10m and the angles are θ1= 30 and θ1= 105Find the (a) x and y components of their vector sum r (b) the magnitude of r and (c) the angle r makes with the positive direction of the x axis

In [7]:
a = 10
b = 10

ang1 = 30
ang2 = ang1+105

print("First Vector x-xcomponent")
x1 = x_comp(a,ang1)
print(x1)
print("First Vector y-xcomponent")
y1 = y_comp(a,ang1)
print(y1)
print("Second Vector x-xcomponent")
x2 = x_comp(b,ang2)
print(x2)
print("Second Vector y-xcomponent")
y2 = y_comp(b,ang2)
print(y2)

First Vector x-xcomponent
8.660254037844387
First Vector y-xcomponent
4.999999999999999
Second Vector x-xcomponent
-7.071067811865475
Second Vector y-xcomponent
7.0710678118654755


In [8]:
print("x-component of Vector R")
x = x1+x2
print(x)
print("x-component of Vector R")
y = y1+y2
print(y)

x-component of Vector R
1.5891862259789127
x-component of Vector R
12.071067811865476


In [9]:
print("Magnitude Of Resultant Vector")
a = magnitude(x,y)
print(a)

Magnitude Of Resultant Vector
12.175228580174414


In [10]:
print("Angle of R-vector with positive x-axis")
degree = tan_angle(x,y)
print("In Degrees:",degree)

Angle of R-vector with positive x-axis
In Degrees: 82.54184519782099


## 3. For the vectors in Fig. 3, with a = 4, b = 3, and c = 5, what are (a) the magnitude and the direction of a X b , (b) the magnitude and) the direction of a X c , and (c) the magnitude and the direction of b X c ?

In [9]:
print("a x b is:")
a = [4, 0, 0]
b = [0, 3, 0]
c = [4, 3, 0]
n.cross(a, b)

a x b is:


array([ 0,  0, 12])

In [10]:
print("a x c is:")
n.cross(a, c)

a x c is:


array([ 0,  0, 12])

In [11]:
print("b x c is:")
n.cross(b, c)

b x c is:


array([  0,   0, -12])

## 4. By Considering the above problem -2 find the (a) a . b (b) a X b (c) angle between a and b

In [11]:
a = 10
b = 10

ang1 = 30
ang2 = 105

r_angle = ang2-ang1

print("dot prodct: ",dot(a, b, r_angle))
print("cross product: ",cross(a, b, ang2))

dot prodct:  25.881904510252074
cross product:  96.59258262890683


## 5. The x component of vector A is 25.0 m and the y component is 40.0 m. (a) What is the magnitude of A (b) What is the angle between the direction of and the positive direction of x?

In [12]:
x = 25.0
y = 40.0
print("Magnitude of A")
print(magnitude(x,y))
print("Angle of A with x_axis")
print(angle(x,y))

Magnitude of A
47.16990566028302
Angle of A with x_axis
58.02403250357966


## 6. A ship sets out to sail to a point 120 km due north. An unexpected storm blows the ship to a point 100 km due east of its starting point. (a) How far and (b) in what direction must it now sail to reach its original destination?

In [20]:
a = 100
b = 120

c = magnitude(a,b)
print("Hypotenus is:",c)
print("therefoe Cos(theta) = B/H")
theta = cos_angle(a, c)
angle = 180-theta
print(angle)

Hypotenus is: 156.20499351813308
therefoe Cos(theta) = B/H
129.78011174914815


## 7. Three vectors a , b and c each have a magnitude of 50 m and lie in an xy plane. Their directions relative to the positive direction of the x axis are 30°, 195°, and 315°, respectively. What are (i) the magnitude and the angle of the vector a+b+c , and (ii) the magnitude and the angle of a-b+c? What are the (iii) magnitude and angle of a fourth vector d such that (a+b ) – (c+d) = 0 ?

In [16]:
a = b = c = 50
ang1 = 30
ang2 = 195
ang3 = 315
print("components of A")
Ax = x_comp(a,ang1)
print("x-component is:",Ax)
Ay = y_comp(a,ang1)
print("y-component is:",Ay)
print("components of B")
Bx = x_comp(b,ang2)
print("x-component is:",Bx)
By = y_comp(b,ang2)
print("y-component is:",By)
print("components of C")
Cx = x_comp(c,ang3)
print("x-component is:",Cx)
Cy = y_comp(c,ang3)
print("y-component is:",Cy)

print("\nFor (a+b+c) ")

Rx = Ax+Bx+Cx
print("\nX-component of Resultant Vector is:",Rx)

Ry = Ay+By+Cy
print("X-component of Resultant Vector is:",Ry)

R = magnitude(Rx, Ry)
print("\nMagnitude of Resultant Vector is: ",R)

angle = tan_angle(Rx, Ry)
print("\nAngle of Resultant Vector is: ",angle)

components of A
x-component is: 43.30127018922194
y-component is: 24.999999999999996
components of B
x-component is: -48.29629131445341
y-component is: -12.94095225512604
components of C
x-component is: 35.35533905932737
y-component is: -35.355339059327385

For (a+b+c) 

X-component of Resultant Vector is: 30.360317934095896
X-component of Resultant Vector is: -23.296291314453427

Magnitude of Resultant Vector is:  38.26834323650899

Angle of Resultant Vector is:  -37.519020544464105


In [17]:
print("\nFor (a-b+c) ")

Rx = Ax-Bx+Cx
print("\nX-component of Resultant Vector is:",Rx)

Ry = Ay-By+Cy
print("X-component of Resultant Vector is:",Ry)

R = magnitude(Rx, Ry)
print("\nMagnitude of Resultant Vector is: ",R)

angle = tan_angle(Rx, Ry)
print("\nAngle of Resultant Vector is: ",angle)


For (a-b+c) 

X-component of Resultant Vector is: 126.95290056300271
X-component of Resultant Vector is: 2.5856131957986506

Magnitude of Resultant Vector is:  126.97922805308725

Angle of Resultant Vector is:  1.1673571470670452


In [18]:
print("\nFor (a+b-c) = d; Find d ")

Rx = Ax+Bx-Cx
print("\nX-component of Resultant Vector is:",Rx)

Ry = Ay+By-Cy
print("X-component of Resultant Vector is:",Ry)

R = magnitude(Rx, Ry)
print("\nMagnitude of Resultant Vector is: ",R)

angle = tan_angle(Rx, Ry)
print("\nAngle of Resultant Vector is: ",angle)


For (a+b-c) = d; Find d 

X-component of Resultant Vector is: -40.350360184558845
X-component of Resultant Vector is: 47.41438680420134

Magnitude of Resultant Vector is:  62.25974335830541

Angle of Resultant Vector is:  -49.626872879261136


## 10. Vector A has a magnitude of 6 units, vector B has a magnitude of 7 units, and A.B has a value of 14. What is the angle between the direction of A and B?

In [23]:
a = 6
b = 7

dot = 14


print("We know A.B = |A||B|Cos(theta)")
degree = cos_angle(dot,(a*b))
print("Angle between A and B is: ",degree)

We know A.B = |A||B|Cos(theta)
Angle between A and B is:  70.56455258641384
